name: moosyl
description: "The Moosyl Flutter SDK is a powerful tool for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi"

homepage: https://github.com/SoftwareSavants/moosyl_flutter
version: 1.0.7

license: MIT

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_hooks: ^0.20.5
  intl: ^0.19.0
  http: ^1.2.2
  provider: ^6.1.2
  modal_bottom_sheet: ^3.0.0
  file_picker: ^8.1.2
  mime: ^2.0.0
  video_player: ^2.8.2
  chewie: ^1.10.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen: ^5.7.0
  build_runner: ^2.4.11
  custom_lint: ^0.7.0

flutter:
  generate: true
  assets:
    - assets/icons/


repository: https://github.com/SoftwareSavants/moosyl_flutter.git

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

screenshots:
  - description: "This screenshot show the available methods"
    path: assets/images/test.png
