name: software_pay
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  riverpod_annotation: ^2.3.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  flutter_gen: ^5.7.0

flutter:
  generate: true
  assets:
    - lib/assets/icons/
