name: software_pay
description:
  "SoftwarePay is a Flutter package designed to simplify and customize payment methods for organizations.
  It supports multiple payment methods, customizable interfaces, and provides hooks for various custom
  payment processing needs. The package integrates seamlessly with Flutter applications, and is designed
  for developers looking for a flexible, secure, and scalable payment solution."
version: 0.0.2

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localization: ^0.2.2
  intl: ^0.18.0
  flutter_svg: ^2.0.10+1
  get_it: ^8.0.0
  http: ^1.2.2
  provider: ^6.1.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_gen: ^5.7.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4

dependency_overrides:
  intl: ^0.18.1

flutter:
  generate: true
  assets:
    - lib/assets/icons/
    - lib/l10n/

repository: https://github.com/just-abdou/SoftwarePay.git
