name: moosyl
description: "Moosyl is a Flutter package designed to simplify and customize payment methods for organizations."
# TODO: rename the package to moosyl
homepage: https://github.com/just-abdou/SoftwarePay.git
version: 0.0.41

license: MIT

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localization: ^0.2.2
  intl: ^0.19.0
  http: ^1.2.2
  provider: ^6.1.2
  flutter_localizations:
    sdk: flutter
  modal_bottom_sheet: ^3.0.0
  file_picker: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_gen: ^5.7.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4

dependency_overrides:
  intl: ^0.18.1

flutter:
  generate: true
  assets:
    - assets/icons/

repository: https://github.com/just-abdou/SoftwarePay.git

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

screenshots:
  - description: "This screenshot show the available methods"
    path: assets/images/test.png
