name: software_pay
description: "SoftwarePay is a Flutter package designed to simplify and customize payment methods for organizations."
homepage: https://github.com/just-abdou/SoftwarePay.git
version: 0.0.13

license: MIT

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localization: ^0.2.2
  intl: ^0.19.0
  http: ^1.2.2
  provider: ^6.1.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_gen: ^5.7.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4

dependency_overrides:
  intl: ^0.18.1

flutter:
  generate: true
  assets:
    - lib/src/assets/icons/
    - lib/src/l10n/

repository: https://github.com/just-abdou/SoftwarePay.git

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
