name: Auto Tag on Pull Request

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from pubspec.yaml
        id: extract-version
        run: |
          # Extract version from pubspec.yaml
          PUBSPEC_VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: *//' | tr -d ' ')
          
          if [ ! -z "$PUBSPEC_VERSION" ]; then
            # Ensure version starts with 'v'
            VERSION_FROM_PUBSPEC="v$PUBSPEC_VERSION"
            echo "version-from-pubspec=$VERSION_FROM_PUBSPEC" >> $GITHUB_OUTPUT
            echo "Found version in pubspec.yaml: $VERSION_FROM_PUBSPEC"
          else
            echo "version-from-pubspec=" >> $GITHUB_OUTPUT
            echo "No version found in pubspec.yaml"
          fi

      - name: Get latest tag
        id: get-latest-tag
        run: |
          # Get the latest tag, or default to v0.0.0 if no tags exist
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "latest-tag=$LATEST_TAG" >> $GITHUB_OUTPUT
          echo "Latest tag: $LATEST_TAG"

      - name: Determine new tag version
        id: determine-tag
        run: |
          VERSION_FROM_PUBSPEC="${{ steps.extract-version.outputs.version-from-pubspec }}"
          LATEST_TAG="${{ steps.get-latest-tag.outputs.latest-tag }}"
          
          if [ ! -z "$VERSION_FROM_PUBSPEC" ]; then
            # Use version from pubspec.yaml
            NEW_TAG="$VERSION_FROM_PUBSPEC"
            echo "Using version from pubspec.yaml: $NEW_TAG"
          else
            # Increment the latest tag
            echo "No version in pubspec.yaml, incrementing latest tag: $LATEST_TAG"
            
            # Remove 'v' prefix if present
            VERSION=${LATEST_TAG#v}
            
            # Split version into parts
            IFS='.' read -ra VERSION_PARTS <<< "$VERSION"
            MAJOR=${VERSION_PARTS[0]:-0}
            MINOR=${VERSION_PARTS[1]:-0}
            PATCH=${VERSION_PARTS[2]:-0}
            
            # Increment patch version
            NEW_PATCH=$((PATCH + 1))
            NEW_TAG="v$MAJOR.$MINOR.$NEW_PATCH"
            echo "Auto-incremented to: $NEW_TAG"
          fi
          
          echo "new-tag=$NEW_TAG" >> $GITHUB_OUTPUT
          echo "Final tag: $NEW_TAG"

      - name: Check if tag exists and create new tag
        run: |
          NEW_TAG="${{ steps.determine-tag.outputs.new-tag }}"
          
          # Check if tag already exists
          if git rev-parse "$NEW_TAG" >/dev/null 2>&1; then
            echo "Tag $NEW_TAG already exists. Skipping tag creation."
            exit 0
          fi
          
          # Check if tag exists on remote
          if git ls-remote --tags origin | grep -q "refs/tags/$NEW_TAG$"; then
            echo "Tag $NEW_TAG already exists on remote. Skipping tag creation."
            exit 0
          fi
          
          # Create and push the tag
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "$NEW_TAG" -m "Auto-generated tag $NEW_TAG from PR #${{ github.event.pull_request.number }}"
          git push origin "$NEW_TAG"
          echo "Created and pushed tag: $NEW_TAG" 