name: Validate

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - main

jobs:
  validate:
    name: 'Validate'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - uses: flutter-actions/setup-flutter@v4

      - name: Install dependencies
        run: dart pub get

      - name: Publish - dry run
        run: dart pub publish --dry-run
